### ISSUE TITLE
compare error

### ISSUE THREAD

**Issue by geraldsamosir** [bsiddiqui/bookshelf-bcrypt#11]
i have try to set this library like your example and it'w work when save to database 

but when i'm try to compare that to check password using this

`User.compare(user.password)`

user.password is normal string password 

thats return  err 

`Error: data and hash arguments required
    at /home/gerald/code/node/openmind/Express-es6-starter/node_modules/bcrypt/bcrypt.js:144:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) `

my setting in my model is 

`Bookshelf.plugin('registry')
Bookshelf.plugin(bookshelfBcrypt)`
 
can you help me  :) or maybe do you have some example  ?

**Comment by geraldsamosir** [comment]
sorry i have to solve  that:D
