### ISSUE TITLE
Error: EmptyResponse on simple find method

### ISSUE THREAD

**Issue by jamesdixon** [bsiddiqui/bookshelf-bcrypt#4]
Hi again :)

I'm running into another strange error that seems to be related to the plugin. When calling a simple `findOne` method where no result is found, I'm seeing the following error:

```
Debug: internal, error
    undefined: EmptyResponse
    at .<anonymous> (/Users/jamesdixon/Projects/scout/platform/api/node_modules/bookshelf/lib/model.js:671:36)
    at bound (domain.js:280:14)
    at Object.runBound (domain.js:293:12)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
From previous event:
    at .<anonymous> (/Users/jamesdixon/Projects/scout/platform/api/node_modules/bookshelf/lib/model.js:669:6)
From previous event:
    at fetch (/Users/jamesdixon/Projects/scout/platform/api/node_modules/bookshelf/lib/model.js:658:17)
    at Function.Bookshelf.Model.extend.findOne (/Users/jamesdixon/Projects/scout/platform/api/models/base.js:129:14)
    at Function.fetchOne (/Users/jamesdixon/Projects/scout/platform/api/models/appointment.js:322:28)
    at fetchOne (/Users/jamesdixon/Projects/scout/platform/api/handlers/business/appointment.js:99:12)
```

In my model (which doesn't even enabled for Bcrypt), I'm simply doing the following call:

```
return Appointment.findOne(data, options);
```

My `findOne` call looks like so:

```
    findOne: function (query, options) {

        query = this.prototype.format(query);
        options = _.assign({ require: true }, options);

        return this
            .where(query)
            .fetch(options);
    }
```

The expected result is a 404 error thrown to the client (instance of `Model.NotFoundError`). However, if I disable the plugin completely, everything works as expected. 

Any ideas what this might be?

Thanks!

**Comment by alanhoff** [comment]
@jamesdixon which `bookshelf-bcrypt`'s version?

**Comment by jamesdixon** [comment]
2.0.1

**Comment by alanhoff** [comment]
Ok could replicate it, thx for the report.

**Comment by jamesdixon** [comment]
Of course. Thanks for the help!

**Comment by alanhoff** [comment]
Fixed in `2.0.2`

**Comment by jamesdixon** [comment]
Thank you, sir. I'll give it a shot!

**Comment by jamesdixon** [comment]
Works beautifully! Thanks again for all of your help 👍
