### ISSUE TITLE
strict mode reserved word

### ISSUE THREAD

**Issue by igoreliasm** [bsiddiqui/bookshelf-bcrypt#8]
Hello there! You know why this problem happened?

```
node_modules/bookshelf-bcrypt/index.js:3
let merge = require('lodash.merge')
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/hilivery-webservice/libs/db.js:8:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/hilivery-webservice/models/users.js:3:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/hilivery-webservice/routes/api.js:5:12)
    at Module._compile (module.js:456:26)
```

**Comment by bsiddiqui** [comment]
@igoreliasm what version of node are you using?

**Comment by igoreliasm** [comment]
@bsiddiqui 
What versions it work?
I am trying update to 4 LTS, but I am having a error with sqlite.

**Comment by bsiddiqui** [comment]
@igoreliasm has to be at least node 4 because that's when ES6 was introduced

**Comment by igoreliasm** [comment]
tks @bsiddiqui.
I should have seen the let, sorry.
when I solve the problem with sqlite I will try it again and reply here.

**Comment by bsiddiqui** [comment]
no prob! closing for now. feel free to re-open if it persists after you upgrade.
happy hacking

**Comment by igoreliasm** [comment]
It worked!
